# TODO
services:
  api:
    image: halftone-api
    build: ./backend
    container_name: halftone-api
    ports:
      - "8080:8080"
#    environment:
#      AWS_SECRET_ACCESS_KEY: /run/secrets/secrets
#      AWS_APP_CLIENT_SECRET: /run/secrets/secrets
    env_file:
      - "./backend/.env"
    depends_on:
      - mongodb
      - redis
#    secrets:
#      - api-secrets
  admin:
    image: halftone-admin:latest
    build: ./frontend-admin
    container_name: halftone-admin
    ports:
      - "80:80"
    env_file:
      - "./backend/.env"
  client:
    image: halftone-client:latest
    build: ./frontend-client
    container_name: halftone-client
    ports:
      - "81:80"
    env_file:
      - "./backend/.env"


  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    environment:
      REDIS_ARGS: ""
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data


volumes:
  mongo-data:
  redis-data:

secrets:
  api-secrets:
      file: ./secrets.txt

