version: "3"

tasks:
  docs:
    cmds:
      - swag i -d ./backend/cmd/halftone,./backend/internal/api --parseDependency --parseInternal
  api:
    cmds:
      - go run ./cmd/halftone/main.go api
  scheduler:
    cmds:
      - go run ./cmd/halftone/main.go scheduler
  client:
    dir: "web"
    cmds:
      - npm run dev
  ginstall:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
  lambdas:
    dir: "lambdas"
    cmds:
      - cd imgd; go mod tidy; GOARCH=amd64 GOOS=linux go build -o bootstrap main.go; zip deployment.zip bootstrap; cd ..
