# TODO
services:
#  api:
#  scheduler:
#  worker:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    environment:
      REDIS_ARGS: ""
    ports:
      - "6379:6379"
      - "8001:8001"

