version: "3"

tasks:
  docs:
    cmds:
      - swag i -d ./cmd/http,./internal/collection
  grun:
    cmds:
      - go run ./cmd/http/main.go
  srun:
    dir: "web"
    cmds:
      - npm run dev
  ginstall:
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@latest
# TODO add dockerfiles, docker compose and add a task cmd to handle it all
