definitions:
  collection.collectionDB:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  collection.createCollectionRequest:
    properties:
      name:
        type: string
    type: object
  collection.createCollectionResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact:
    name: Michał Klemens
  description: An example template of a Golang backend API using Fiber and MongoDB
  title: Hello World Template
  version: "0.1"
paths:
  /collections:
    get:
      consumes:
      - '*/*'
      description: gets all collections.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/collection.collectionDB'
            type: array
      summary: Get all collections.
      tags:
      - collections
    post:
      consumes:
      - application/json
      description: creates one collection.
      parameters:
      - description: Collection to create
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/collection.createCollectionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/collection.createCollectionResponse'
      summary: Create one collection.
      tags:
      - collections
swagger: "2.0"
