definitions:
  collection.createCollectionRequest:
    properties:
      name:
        type: string
    type: object
  collection.createCollectionResponse:
    properties:
      id:
        type: string
    type: object
  domain.CollectionDB:
    properties:
      galleries:
        items:
          $ref: '#/definitions/domain.GalleryDB'
        type: array
      id:
        type: string
      name:
        type: string
    type: object
  domain.GalleryDB:
    properties:
      expiry_date:
        type: integer
      id:
        type: string
      name:
        type: string
    type: object
  fiber.Map:
    additionalProperties: true
    type: object
  gallery.createGalleryRequest:
    properties:
      expiry_date:
        example: "2023-12-31T23:59:59Z"
        type: string
      name:
        example: Example Gallery
        type: string
    type: object
  gallery.createGalleryResponse:
    properties:
      id:
        type: string
    type: object
  gallery.generateQrRequest:
    description: Request body for generating a QR code
    properties:
      url:
        description: URL to be encoded in the QR code
        example: https://example.com
        type: string
    type: object
  qr.QrGenerationRequest:
    description: Request body for generating a QR code
    properties:
      url:
        description: URL to be encoded in the QR code
        example: https://example.com
        type: string
    type: object
info:
  contact:
    name: Michał Klemens
  description: Image gallery that provides uploading images
  title: Studio Ginger - QR code generator
  version: "0.1"
paths:
  /collections:
    get:
      consumes:
      - '*/*'
      description: Gets all collections
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.CollectionDB'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get all collections
      tags:
      - collections
    post:
      consumes:
      - application/json
      description: Creates one collection
      parameters:
      - description: Collection to create
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/collection.createCollectionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/collection.createCollectionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create one collection
      tags:
      - collections
  /collections/{collectionId}/galleries:
    get:
      consumes:
      - '*/*'
      description: gets all galleries of a collection with collectionId.
      parameters:
      - description: Collection ID
        in: path
        name: collectionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.GalleryDB'
            type: array
      summary: Get all galleries of a collection.
      tags:
      - collections
    post:
      consumes:
      - application/json
      description: Creates one gallery in collection with collectionId
      parameters:
      - description: Gallery to create
        in: body
        name: gallery
        required: true
        schema:
          $ref: '#/definitions/gallery.createGalleryRequest'
      - description: Collection ID
        in: path
        name: collectionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/gallery.createGalleryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create one gallery
      tags:
      - collections
  /collections/{collectionId}/galleries/{galleryId}/generate:
    post:
      consumes:
      - application/json
      description: Generate a QR code from a given URL
      parameters:
      - description: QR Generation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/gallery.generateQrRequest'
      - description: Collection ID
        in: path
        name: collectionId
        required: true
        type: string
      - description: Gallery ID
        in: path
        name: galleryId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Generate QR code
      tags:
      - QR
  /qr:
    post:
      consumes:
      - application/json
      description: Generate a QR code from a given URL
      parameters:
      - description: QR Generation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/qr.QrGenerationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Generate QR code
      tags:
      - QR
swagger: "2.0"
