definitions:
  api.createCollectionRequest:
    properties:
      name:
        type: string
    type: object
  api.createCollectionResponse:
    properties:
      id:
        type: string
    type: object
  api.createGalleryRequest:
    properties:
      name:
        example: Example Gallery
        type: string
    type: object
  api.createGalleryResponse:
    properties:
      id:
        type: string
    type: object
  api.generateQrRequest:
    description: Request body for generating a QR code
    properties:
      url:
        description: URL to be encoded in the QR code
        example: https://example.com
        type: string
    type: object
  api.getPhotoResponse:
    properties:
      createdAt:
        type: integer
      originalFilename:
        type: string
      updatedAt:
        type: integer
      url:
        type: string
    type: object
  api.photoUploadRequest:
    properties:
      originalFilename:
        type: string
    type: object
  api.photoUploadResponse:
    properties:
      originalFilename:
        type: string
      presignedPostRequest:
        $ref: '#/definitions/s3.PresignedPostRequest'
    type: object
  api.updateCollectionRequest:
    properties:
      name:
        type: string
    type: object
  api.updateGalleryRequest:
    type: object
  domain.CollectionDB:
    properties:
      createdAt:
        type: integer
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: integer
    type: object
  domain.GalleryDB:
    properties:
      collectionId:
        type: string
      createdAt:
        type: integer
      id:
        type: string
      name:
        type: string
      passwordAttempts:
        type: integer
      passwordHash:
        type: string
      sharingEnabled:
        type: boolean
      sharingExpiryDate:
        type: integer
      updatedAt:
        type: integer
    type: object
  domain.PhotoDB:
    properties:
      collectionId:
        type: string
      createdAt:
        type: integer
      galleryId:
        type: string
      id:
        type: string
      originalFilename:
        type: string
      status:
        $ref: '#/definitions/domain.PhotoStatus'
      updatedAt:
        type: integer
    type: object
  domain.PhotoStatus:
    enum:
    - 0
    - 1
    type: integer
    x-enum-varnames:
    - Pending
    - Uploaded
  fiber.Map:
    additionalProperties: true
    type: object
  s3.PresignedPostRequest:
    properties:
      url:
        description: Represents the Base URL to make a request to
        type: string
      values:
        additionalProperties:
          type: string
        description: |-
          Values is a key-value map of values to be sent as FormData
          these values are not encoded
        type: object
    type: object
info:
  contact:
    name: Michał Klemens
  title: Image library
  version: "0.1"
paths:
  /api/v1/collections:
    get:
      consumes:
      - '*/*'
      description: Gets all collections
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.CollectionDB'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get collections
      tags:
      - collections
    post:
      consumes:
      - application/json
      description: Creates one collection
      parameters:
      - description: Collection to create
        in: body
        name: collections
        required: true
        schema:
          $ref: '#/definitions/api.createCollectionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.createCollectionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create collection
      tags:
      - collections
  /api/v1/collections/{collectionId}:
    delete:
      consumes:
      - '*/*'
      description: Deletes specific collection
      parameters:
      - description: Collection ID
        in: path
        name: collectionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Delete collection
      tags:
      - collections
    get:
      consumes:
      - '*/*'
      description: Gets specific collection
      parameters:
      - description: Collection ID
        in: path
        name: collectionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.CollectionDB'
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get collection
      tags:
      - collections
    put:
      consumes:
      - '*/*'
      description: Updates specific collection
      parameters:
      - description: Collection update request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.updateCollectionRequest'
      - description: Collection ID
        in: path
        name: collectionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.CollectionDB'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/fiber.Map'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Update collection
      tags:
      - collections
  /api/v1/collections/{collectionId}/galleries:
    get:
      consumes:
      - '*/*'
      description: gets all galleries of a collection with collectionId.
      parameters:
      - description: Collection ID
        in: path
        name: collectionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.GalleryDB'
            type: array
      summary: Get all galleries of a collection.
      tags:
      - collections
    post:
      consumes:
      - application/json
      description: Creates one gallery in collection with collectionId
      parameters:
      - description: Gallery to create
        in: body
        name: galleries
        required: true
        schema:
          $ref: '#/definitions/api.createGalleryRequest'
      - description: Collection ID
        in: path
        name: collectionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.createGalleryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Create one gallery
      tags:
      - collections
  /api/v1/collections/{collectionId}/galleryCount:
    get:
      consumes:
      - application/json
      description: Returns the total number of galleries in a specific collection
      parameters:
      - description: Collection ID (MongoDB ObjectID hex string)
        in: path
        name: collectionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Gallery count
          schema:
            $ref: '#/definitions/fiber.Map'
        "404":
          description: Collection not found or invalid ID format
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get gallery count for a collection
      tags:
      - collections
  /api/v1/galleries/{galleryId}:
    delete:
      consumes:
      - application/json
      description: Deletes a specific gallery
      parameters:
      - description: Gallery ID
        in: path
        name: galleryId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Delete gallery
      tags:
      - galleries
    get:
      consumes:
      - application/json
      description: Retrieves a specific gallery by its ID
      parameters:
      - description: Gallery ID
        in: path
        name: galleryId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.GalleryDB'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get gallery
      tags:
      - galleries
    put:
      consumes:
      - application/json
      description: Updates an existing gallery's information
      parameters:
      - description: Gallery ID
        in: path
        name: galleryId
        required: true
        type: string
      - description: Gallery update request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.updateGalleryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/fiber.Map'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/fiber.Map'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Update gallery
      tags:
      - galleries
  /api/v1/galleries/{galleryId}/photos:
    get:
      consumes:
      - application/json
      description: Retrieves all photos from a specific gallery, including their signed
        URLs
      parameters:
      - description: Gallery ID (MongoDB ObjectID)
        format: objectid
        in: path
        name: galleryId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.getPhotoResponse'
        "404":
          description: Gallery not found or invalid ID
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Server error while retrieving photos
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Get gallery photos
      tags:
      - photos
    post:
      consumes:
      - application/json
      description: Creates new photo entries in a gallery and returns pre-signed URLs
        for uploading the actual photo files
      parameters:
      - description: Gallery ID
        format: objectId
        in: path
        name: galleryId
        required: true
        type: string
      - description: Photo upload requests
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/api.photoUploadRequest'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Successfully created photo entries with upload URLs
          schema:
            items:
              $ref: '#/definitions/api.photoUploadResponse'
            type: array
        "400":
          description: Invalid request body or gallery ID
          schema:
            $ref: '#/definitions/fiber.Map'
        "404":
          description: Gallery not found
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Upload photos to a gallery
      tags:
      - photos
      - gallery
  /api/v1/galleries/{galleryId}/qr:
    post:
      consumes:
      - application/json
      description: Generate a QR code from a given URL
      parameters:
      - description: QR Generation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.generateQrRequest'
      - description: Collection ID
        in: path
        name: collectionId
        required: true
        type: string
      - description: Gallery ID
        in: path
        name: galleryId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Generate QR code
      tags:
      - QR
  /api/v1/photos/{photoId}/confirm:
    put:
      consumes:
      - application/json
      description: Confirms that a photo has been successfully uploaded by updating
        its status
      parameters:
      - description: Photo ID (MongoDB ObjectID)
        format: objectid
        in: path
        name: photoId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.PhotoDB'
        "404":
          description: Photo not found or invalid ID
          schema:
            $ref: '#/definitions/fiber.Map'
        "500":
          description: Server error while confirming upload
          schema:
            $ref: '#/definitions/fiber.Map'
      summary: Confirm photo upload
      tags:
      - photos
swagger: "2.0"
