name: Deploy with CodeDeploy

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1
  ENVIRONMENT: prod
  ECR_FRONTEND_REPOSITORY_NAME: halftone-client
  ECR_BACKEND_REPOSITORY_NAME: halftone-api

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            backend:
              - 'application/backend/**'
            frontend:
              - 'application/client/**'
            infrastructure:
              - 'infrastructure/**'

  deploy-infrastructure:
    needs: changes
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./infrastructure/environments/cloud
    outputs:
      codedeploy_app_name: ${{ steps.terraform-output.outputs.codedeploy_app_name }}
      codedeploy_deployment_group: ${{ steps.terraform-output.outputs.codedeploy_deployment_group }}
      ecs_cluster_name: ${{ steps.terraform-output.outputs.ecs_cluster_name }}
      task_definition_family: ${{ steps.terraform-output.outputs.task_definition_family }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0
          terraform_wrapper: false
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_docdb_master_username: ${{ secrets.DOCDB_MASTER_USERNAME }}
          TF_VAR_docdb_master_password: ${{ secrets.DOCDB_MASTER_PASSWORD }}

      - name: Get Terraform Outputs
        id: terraform-output
        run: |
          echo "codedeploy_app_name=$(terraform output -raw codedeploy_app_name)" >> $GITHUB_OUTPUT
          echo "codedeploy_deployment_group=$(terraform output -raw codedeploy_deployment_group_name)" >> $GITHUB_OUTPUT
          echo "ecs_cluster_name=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_OUTPUT
          echo "task_definition_family=$(terraform output -raw task_definition_family)" >> $GITHUB_OUTPUT

  deploy-backend:
    needs: [ changes, deploy-infrastructure ]
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./application/backend
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get ECR repository URI
        id: ecr-repo
        run: |
          REPO_URI=$(aws ecr describe-repositories --repository-names ${{ env.ECR_BACKEND_REPOSITORY_NAME }} --query 'repositories[0].repositoryUri' --output text)
          echo "repository_uri=$REPO_URI" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REPOSITORY: ${{ steps.ecr-repo.outputs.repository_uri }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Use commit SHA for traceability
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REPOSITORY:latest .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REPOSITORY:latest

      - name: Create new task definition revision
        id: task-def
        env:
          ECR_REPOSITORY: ${{ steps.ecr-repo.outputs.repository_uri }}
          IMAGE_TAG: ${{ github.sha }}
          TASK_FAMILY: ${{ needs.deploy-infrastructure.outputs.task_definition_family }}
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          
          # Verify task family exists
          if ! aws ecs describe-task-definition --task-definition $TASK_FAMILY >/dev/null 2>&1; then
            echo "Task definition family $TASK_FAMILY not found!"
            exit 1
          fi
          
          # Get current task definition
          TASK_DEFINITION=$(aws ecs describe-task-definition \
            --task-definition $TASK_FAMILY \
            --query 'taskDefinition' \
            --output json)
          
          # Update image URI in task definition
          NEW_TASK_DEF=$(echo $TASK_DEFINITION | jq --arg IMAGE "$ECR_REPOSITORY:$IMAGE_TAG" \
            '.containerDefinitions[0].image = $IMAGE | 
             del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .placementConstraints, .compatibilities, .registeredAt, .registeredBy)')
          
          # Register new task definition
          NEW_REVISION=$(aws ecs register-task-definition \
            --cli-input-json "$NEW_TASK_DEF" \
            --query 'taskDefinition.revision' \
            --output text)
          
          echo "revision=$NEW_REVISION" >> $GITHUB_OUTPUT
          echo "task_definition_arn=arn:aws:ecs:${{ env.AWS_REGION }}:${AWS_ACCOUNT_ID}:task-definition/$TASK_FAMILY:$NEW_REVISION" >> $GITHUB_OUTPUT

      - name: Create CodeDeploy deployment
        env:
          CODEDEPLOY_APP: ${{ needs.deploy-infrastructure.outputs.codedeploy_app_name }}
          DEPLOYMENT_GROUP: ${{ needs.deploy-infrastructure.outputs.codedeploy_deployment_group }}
          TASK_DEFINITION_ARN: ${{ steps.task-def.outputs.task_definition_arn }}
        run: |
          APPSPEC_CONTENT='{
            "version": "0.0",
              "Resources": [
                {
                  "TargetService": {
                    "Type": "AWS::ECS::Service",
                    "Properties": {
                      "TaskDefinition": "'$TASK_DEFINITION_ARN'",
                      "LoadBalancerInfo": {
                        "ContainerName": "api",
                        "ContainerPort": 8080
                      }
                    }
                  }
                }
              ]
            }'
            
          echo "AppSpec content:"
          echo "$APPSPEC_CONTENT" | jq .
          
          cat > deployment.json << EOF
          {
            "applicationName": "$CODEDEPLOY_APP",
            "deploymentGroupName": "$DEPLOYMENT_GROUP",
            "revision": {
              "revisionType": "AppSpecContent",
              "appSpecContent": {
                "content": $(echo "$APPSPEC_CONTENT" | jq -c .)
              }
            }
          }
          EOF
          
          echo "Deployment configuration:"
          cat deployment.json | jq .
          
          DEPLOYMENT_ID=$(aws deploy create-deployment \
            --cli-input-json file://deployment.json \
            --query 'deploymentId' \
            --output text)
          
          echo "Created deployment with ID: $DEPLOYMENT_ID"
          
          echo "Waiting for deployment to complete..."
          aws deploy wait deployment-successful --deployment-id $DEPLOYMENT_ID
          
          echo "Deployment completed successfully!"

  deploy-frontend:
    needs: [changes, deploy-infrastructure]
    if: needs.changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: ./application/client
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./application/client/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get frontend ECR repository URI
        id: ecr-repo
        run: |
          REPO_URI=$(aws ecr describe-repositories --repository-names ${{ env.ECR_FRONTEND_REPOSITORY_NAME }} --query 'repositories[0].repositoryUri' --output text)
          echo "repository_uri=$REPO_URI" >> $GITHUB_OUTPUT

      - name: Build and push frontend Docker image
        env:
          ECR_REPOSITORY: ${{ steps.ecr-repo.outputs.repository_uri }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REPOSITORY:latest .
          docker push $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      - name: Update ECS frontend service
        run: |
          # Force new deployment for frontend (using rolling deployment)
          aws ecs update-service \
            --cluster ${{ env.ENVIRONMENT }}-cluster \
            --service ${{ env.ENVIRONMENT }}-client \
            --force-new-deployment